permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: rdiscount
markdown: kramdown

# 作者信息
author: 
  name: 任昌伟
  email: small_pupil@126.com
  link: 
  weibo: 
  github: http://ivanreen.github.io

# 站点信息
title: 任昌伟的博客 
description: 任昌伟的博客
url: http://ivanreen.github.io
rss_url: 

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.jpg
favicon: /public/upload/gavatar/favicon.ico

# gitment
gitment:
  id: 8fad32fc7747e92dd9d7
  secret: ad98ead5cde480988d75d10101912aea81329345

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - Docker

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
plugins:
- jekyll-paginate
